// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGXaJyu63mnidlZJBfjp-SXArCaoTVqcs',
    appId: '1:751984424318:web:cf35454acb60d6fd74af2f',
    messagingSenderId: '751984424318',
    projectId: 'talent-crm-app',
    authDomain: 'talent-crm-app.firebaseapp.com',
    storageBucket: 'talent-crm-app.firebasestorage.app',
    measurementId: 'G-LLL834T786',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZP8dMr5IR9sdaDImuhgzqPP87kgtKPjA',
    appId: '1:751984424318:android:5f75d74cb12b5b5574af2f',
    messagingSenderId: '751984424318',
    projectId: 'talent-crm-app',
    storageBucket: 'talent-crm-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPmTgv8VpnXhlZ_p74Jcxw-bh4nlbHCq4',
    appId: '1:751984424318:ios:59e20558093ec55774af2f',
    messagingSenderId: '751984424318',
    projectId: 'talent-crm-app',
    storageBucket: 'talent-crm-app.firebasestorage.app',
    iosClientId: '751984424318-3b3k2lh74hpe80bftlmvog7djein53d6.apps.googleusercontent.com',
    iosBundleId: 'com.example.talentCrmApp',
  );

}
