// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web. '
        'This app is currently restricted to Android and iOS until a '
        'secure web Firebase configuration is added.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqBz3dDDLykIa85KvYco8HzW_zwtXhPRw',
    appId: '1:751984424318:android:03e77d1977870b1074af2f',
    messagingSenderId: '751984424318',
    projectId: 'talent-crm-app',
    storageBucket: 'talent-crm-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPmTgv8VpnXhlZ_p74Jcxw-bh4nlbHCq4',
    appId: '1:751984424318:ios:fdfeada69894002d74af2f',
    messagingSenderId: '751984424318',
    projectId: 'talent-crm-app',
    storageBucket: 'talent-crm-app.firebasestorage.app',
    iosClientId: '751984424318-5vpnq5d9p3v2u9ja5m0fs7imu6qm7kic.apps.googleusercontent.com',
    iosBundleId: 'com.ariadnichioquetta.talentcrm',
  );

}
